<a href="https://colab.research.google.com/github/ducodbs0516/pdm18/blob/main/numpy/numpy_2_array2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# numpy
## concatenate()를 이용한 배열 결합
> [numpy 배열 합치기, concatenate 함수](https://m.blog.naver.com/PostView.nhn?blogId=qbxlvnf11&logNo=221490583222&categoryNo=0&proxyReferer=https%3A%2F%2Fwww.google.com%2F)

In [1]:
import numpy as np

In [2]:
ar1 = np.array(range(1,5)).reshape(2,2)
ar1

array([[1, 2],
       [3, 4]])

In [3]:
ar1.shape

(2, 2)

In [7]:
np.array(range(5,11))  # 1차원 배열

array([ 5,  6,  7,  8,  9, 10])

In [4]:
ar2 = np.array(range(5,11)).reshape(2,3)  # np.array(range(5,11)).reshape(-1,3)
ar2

array([[ 5,  6,  7],
       [ 8,  9, 10]])

In [5]:
ar2.shape  # 2 X 3 array

(2, 3)

In [12]:
print(ar1)
print(ar2)

[[1 2]
 [3 4]]
[[ 5  6  7]
 [ 8  9 10]]


---

## concatenate()를 이용한 배열 합치기


- concatenate(array1, array2, axis = 0)
- concatenate(array1, array2, axis = 1)
- concatenate(array1, array2, axis = None)

In [8]:
np.concatenate((ar1,ar1), axis=0) # 각 배열을 행 단위로 출력

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [13]:
np.concatenate((ar1,ar1,ar1), axis=0) 

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [9]:
np.concatenate((ar1,ar1), axis=1) # 각 배열을 열 단위로 출력

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [14]:
np.concatenate((ar1,ar1), axis=None) # axis=None 모든 항목들을 1차원으로 확장

array([1, 2, 3, 4, 1, 2, 3, 4])

### ar2에 대하여도 배열합치기를 해보시오.

In [22]:
# Your code here!
print(np.concatenate((ar2,ar2), axis=0))
print(np.concatenate((ar2,ar2), axis=1))
print(np.concatenate((ar2,ar2,ar2), axis=1))
print(np.concatenate((ar2,ar2), axis=None))

[[ 5  6  7]
 [ 8  9 10]
 [ 5  6  7]
 [ 8  9 10]]
[[ 5  6  7  5  6  7]
 [ 8  9 10  8  9 10]]
[[ 5  6  7  5  6  7  5  6  7]
 [ 8  9 10  8  9 10  8  9 10]]
[ 5  6  7  8  9 10  5  6  7  8  9 10]


### Error in concatenation

In [24]:
np.concatenate((ar1,ar2), axis=0)  # ValueError: along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3 
# 두 배열의 열의 개수가 같아야 함.

ValueError: ignored

> ar1의 열의 갯수 == ar2의 열의 갯수

In [25]:
ar1.shape, ar2.shape

((2, 2), (2, 3))

In [26]:
ar2.T.shape # 전치

(3, 2)

In [27]:
np.concatenate((ar1,ar2.T), axis=0)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  8],
       [ 6,  9],
       [ 7, 10]])

### concatenate(array1, array2, axis = 1)

In [28]:
np.concatenate((ar1,ar2), axis=1) # 열 단위로 확장

array([[ 1,  2,  5,  6,  7],
       [ 3,  4,  8,  9, 10]])



---



---



## [복습] numpy 배열 연산: broadcasting
> [파이썬 Numpy 라이브러리 (5) Broadcasting|작성자 예비개발자](https://blog.naver.com/qbxlvnf11/221509303462)

In [29]:
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])
a * b   # elementwise multiplication
# [출처] 파이썬 Numpy 라이브러리 (5) Broadcasting|작성자 예비개발자


array([2., 4., 6.])

In [30]:
a = np.array([1.0, 2.0, 3.0])
b = 2.0
a * b   # broadcasted multiplication


array([2., 4., 6.])

> 차원이 다른 두 개의 피연산자를 산술 연산할 때는 원래 연산이 불가능합니다.
하지만, 연산이 가능하도록 배열 b가 브로드캐스팅이 되어 numpy array ([2.0, 2.0, 2.0])으로 확장됩니다.

### 2차원 broadcasting

In [31]:
a = np.array([[ 0.0,  0.0,  0.0],
              [10.0, 10.0, 10.0],
              [20.0, 20.0, 20.0],
              [30.0, 30.0, 30.0]])

b = np.array([1.0, 2.0, 3.0])

a + b

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [32]:
(a+b).shape

(4, 3)

In [37]:
from numpy import array, newaxis
a = array([0.0, 10.0, 20.0, 30.0])
b = array([1.0, 2.0, 3.0])
#c = a + b # ValueError: operands could not be broadcast together with shapes a ->(4,) b ->(3,) 
c = a[:,newaxis] + b # newaxis 행벡터를 열벡터로 변경
c


array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [34]:
c.shape

(4, 3)

## numpy statistics
> [numpy: 기술 통계](https://datascienceschool.net/01%20python/03.04%20%EA%B8%B0%EC%88%A0%20%ED%86%B5%EA%B3%84.html)
- min(), max()
- mean(), median(), var(), std()

In [39]:
# a = np.array(list(range(1,10)))
a = np.arange(1,10)   
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
# np.min, np.max
a.min(), a.max()

(1, 9)

In [43]:
# array.min(), array.max()
np.min(a), np.max(a)

(1, 9)

In [49]:
# mean() and median()
a.mean(), np.mean(a)#, a.median()

(5.0, 5.0)

In [50]:
# median()
np.median(a)

5.0

In [55]:
# var(), std()
a.var(), a.std()

(6.666666666666667, 2.581988897471611)

In [57]:
np.var(a), np.std(a)

(6.666666666666667, 2.581988897471611)

## 2차원 배열의 기술 통계
- axis = 0
- axis = 1

In [58]:
d2arr = np.arange(1,10).reshape(-1,3)
d2arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
d2arr.max()

9

In [60]:
d2arr.max(axis=0) # 행에 대해 가장 큰 값

array([7, 8, 9])

In [61]:
d2arr.max(axis=1) # 열에 대해 가장 큰 값

array([3, 6, 9])

In [63]:
print(d2arr.min(axis=None))
print(d2arr.min(axis=0))
print(d2arr.min(axis=1))

1
[1 2 3]
[1 4 7]


## [DIY: 도전과제]
- axis = None, 1, 2 에 따른 평균을 구하시오.

In [64]:
# Your code here!
print(d2arr.mean(axis=None))
print(d2arr.mean(axis=0))
print(d2arr.mean(axis=1))

5.0
[4. 5. 6.]
[2. 5. 8.]


In [66]:
print(np.mean(d2arr,axis=None))
print(np.mean(d2arr,axis=0))
print(np.mean(d2arr,axis=1))

5.0
[4. 5. 6.]
[2. 5. 8.]
